
/**
 **************************************************************************************
 * @file    user_defined_effect_api.h
 * @brief   interface for user defined effect algorithm
 *          Automatically generated by the script, no manual modification required.
 *
 * @author  Castle Cai
 * @version V1.0.0
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 **************************************************************************************
 */

#include "roboeffect_api.h"
#include "roboeffect_config.h"


#include "simple_gain.h" 




//Add SIMPLE_GAIN_INFO_DATA to USER_DEFINED_LIBS_DATA
#define SIMPLE_GAIN_INFO_DATA \
0x38, 0x00, \
0x01, 0x00, 0x00, \
0x0B, \
0x73, 0x69, 0x6D, 0x70, 0x6C, 0x65, 0x5F, 0x67, 0x61, 0x69, 0x6E, \
0x02, \
0x03, \
0x00, \
0x03, \
0x02, \
0x04, \
0x6D, 0x75, 0x74, 0x65, \
0x00, \
0x00, 0x00, \
0x00, 0x00, \
0x04, \
0x67, 0x61, 0x69, 0x6E, \
0x02, \
0xD8, 0xDC, \
0xB0, 0x04, \
0x0A, 0x00, \
0x00, 0x00, \
0x00, 0x00, \
0x00, \
0x01, \
0x02, \
0x64, 0x42, \
0x02, \
0x64, 0x00, \
0x00, \
0x00, 

//simple_gain interface
bool roboeffect_simple_gain_init_if(void *node);
bool roboeffect_simple_gain_config_if(void *node, int16_t *new_param, uint8_t param_num, uint8_t len);
bool roboeffect_simple_gain_apply_if(void *node, int16_t *pcm_in1, int16_t *pcm_in2, int16_t *pcm_out, int32_t n);
int32_t roboeffect_simple_gain_scratch_size(uint32_t sample_rate, uint16_t frame_size, uint16_t width, uint8_t ch_num, int16_t *parameters);


//Add SIMPLE_GAIN_INTERFACE to USER_DEFINED_INTERFACE
#define SIMPLE_GAIN_INTERFACE \
	{ROBOEFFECT_SIMPLE_GAIN, ROBOEFFECT_CH_MONO_STEREO, FZ_ANY, 2, (sizeof(simple_gain_struct)),\
	roboeffect_simple_gain_init_if, roboeffect_simple_gain_config_if, roboeffect_simple_gain_apply_if, NULL,\
	},


#define USER_DEFINED_INTERFACE \
	SIMPLE_GAIN_INTERFACE

#define USER_DEFINED_LIBS_DATA \
	SIMPLE_GAIN_INFO_DATA

typedef enum _roboeffect_user_effect_type_enum
{
	/*Add user define effect ID here*/
	ROBOEFFECT_SIMPLE_GAIN = ROBOEFFECT_USER_DEFINED_EFFECT_BEGIN,
	ROBOEFFECT_TOTAL_MAX,
} roboeffect_user_effect_type_enum;
